<a href="https://colab.research.google.com/github/PedroMesquitaIsidoro/RedesNeurais/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# o objetivo desse notebook eh aprender o basico de numpy
import numpy as np

# **Numpy Array**

In [15]:
#Como criar um array NumPy vazio e completo?

#Vazio
array_vazio = np.empty((3,3))
print(array_vazio)

[[4.67983166e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [16]:
#completo
array_completo = np.full((3,3), 17)
print(array_completo)

[[17 17 17]
 [17 17 17]
 [17 17 17]]


In [18]:
#Crie uma matriz Numpy preenchida com todos os zeros
matriz_zero = np.zeros((3,3))
print(matriz_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
#Verifique se um array Numpy contém uma linha especificada
array_exemplo = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

linha_procurada = np.array([4, 5, 6])

linha_esta_no_array = np.any(np.all(array_exemplo == linha_procurada, axis=1))

if linha_esta_no_array:
    print("A linha está no array.")
else:
    print("A linha não está no array.")



A linha está no array.
